# Generated by Django 2.2.5 on 2019-09-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_Campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('article', models.TextField()),
            ],
        ),
    ]
