# Generated by Django 2.2.5 on 2019-09-23 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email_Campaign', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 15, 19, 5, 334679)),
        ),
    ]
